### ISSUE TITLE
Add gitpython for par file shuffling

### ISSUE THREAD

**Issue by rossjjennings** [ipta/pulsar-env#4]
The script I'm writing to automatically move around par files and stage changes makes use of [gitpython](https://gitpython.readthedocs.io/en/stable/intro.html), so we'll have to add that to the environment. It's installable through conda-forge, so this shouldn't be too hard to do.

**Comment by JPGlaser** [comment]
This has been added to PR #8 

~ Joe G.

**Comment by JPGlaser** [comment]
Fixed in https://github.com/ipta/pulsar-env/pull/8 which is now merged.
