### ISSUE TITLE
Add note for installation on Apple Silicon

### ISSUE THREAD

**Issue by gooddc** [ipta/pulsar-env#9]
We really want this to be a straightforward/easy/student-friendly setup, so I think it's probably worth adding a note/link to rosetta instructions for Apple Silicon machines.

**Comment by gooddc** [comment]
Leaving this note for myself as much as anything, but this is the link Aaron J. provided for installing on Apple silicon: 
https://conda-forge.org/docs/user/tipsandtricks/#installing-apple-intel-packages-on-apple-silicon

**Comment by golamshaifullah** [comment]
For ease of use the first instruction to try is:

micromamba env create --platform osx-64 --file anaconda-env.yml

Closing this issue.

**Comment by golamshaifullah** [comment]
The same instruction is now in the readme.
